# Generated by Django 4.0.3 on 2022-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizendetails',
            name='Conditions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
