# Generated by Django 4.0.3 on 2022-06-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_citizendetails_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizendetails',
            name='ZipCode',
            field=models.IntegerField(null=True),
        ),
    ]
